apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::468457242339:role/eks-workers-dev
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::468457242339:role/GitHubActionsCICDrole
      username: github-actions
      groups:
        - system:masters
    - rolearn: arn:aws:iam::468457242339:role/iam-role-eks
      username: admin
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

