apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-resource-deployment
spec:
  replicas: 40
  selector:
    matchLabels:
      app: low-resource-app
  template:
    metadata:
      labels:
        app: low-resource-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

